### PR TITLE
Changed v0.1 to 0.1 in LUIS Section

### PR DESCRIPTION
**Pull request by arafattehsin**
It should be v0.1 as when it's used in conjunction with dispatch tool, it gives an error.

Fixes #

## Proposed Changes

  - 
  -
  -

### CODE REVIEW

**Comment by cleemullins** [comment]
@arafattehsin Can you take case of the licence check, so we can merge this in? :) Thanks!

**Comment by cleemullins** [comment]
@arafattehsin just click on the line that reads "**license/cla ** Expected — Waiting for status to be reported". Should be pretty straight forward from there.

**Comment by arafattehsin** [comment]
untitled
Unfortunately, that whole line is not clickable at all. Just attaching my screenshot for the reference.

**Comment by arafattehsin** [comment]
There has been an issue lately and I am not sure if it's related to this: https://blog.travis-ci.com/2018-09-27-deprecating-github-commit-status-api-for-github-apps-managed-repositories

**Comment by cleemullins** [comment]
Closing PR as it's very old. 

@arafattehsin if this is still relevant, please open a new PR. Hopefully the license check will work properly for you this time around.

**Pull request closed without merging**
