### PR TITLE
Workaround for auto-provision failure of ApplicationId

### LINKED ISSUE #596: msbot clone services fails to provision MSA id
When running clone services:

```shell
msbot clone services --name "SB_EnterpriseBot" --luisAuthoringKey "REDACTED" --folder "DeploymentScripts\msbotClone" --location "westeurope" --verbose
```

Customer receives this error 

"ERROR: Unable to provision MSA id automatically. Please pass them in as parameters and try again"

Verbose logs below:

[msbot] The following services will be created by this operation:
Service Location SKU Resource Group
Azure App Site Plan westeurope S1 SB_EnterpriseBot
Azure AppInsights Service West Europe F0 SB_EnterpriseBot
Azure Blob Storage Service westeurope Standard_LRS SB_EnterpriseBot
Azure Bot Service Registration Global SB_EnterpriseBot
Azure CosmosDB Service westeurope 1 write region SB_EnterpriseBot
Azure LUIS Cognitive Service westeurope S0 SB_EnterpriseBot
Azure LUIS Cognitive Service westeurope S0 SB_EnterpriseBot
(Dispatch)
Azure QnA Maker Service westus S0 SB_EnterpriseBot
Azure Search Service westeurope Standard SB_EnterpriseBot
Azure WebApp Service (Bot) westeurope SB_EnterpriseBot
Azure WebApp Service (QnA) westeurope SB_EnterpriseBot
Would you like to perform this operation? [y/n]y
[msbot] Checking az botservice version
[msbot] az -v
[msbot] Fetching subscription account
[msbot] az account show
[msbot] Creating resources in subscription: SBI-MVP-AzureSubscription **REDACTED**
[msbot] Creating Azure group [SB_EnterpriseBot]
[msbot] az group create -g SB_EnterpriseBot -l westeurope
[msbot] Creating Azure Bot Service [SB_EnterpriseBot]
[msbot] az bot create -g SB_EnterpriseBot --name SB_EnterpriseBot --kind webapp --location westeurope --insights-location "West Europe" --version v4
[msbot] [az bot] To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code C2Y6LR2HT to authenticate.
[msbot] az bot create -g SB_EnterpriseBot --name SB_EnterpriseBot --kind webapp --location westeurope --insights-location "West Europe" --version v4 exit code: 1
WARNING: The behavior of this command has been altered by the following extension: botservice
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code *REDACTED* to authenticate.
ERROR: Unable to provision MSA id automatically. Please pass them in as parameters and try again.
[msbot] Usage: msbot clone services [options]
allows you to clone all of the services a bot into a new azure resource group
Options:
-n, --name name of new bot
-f, --folder path to folder containing exported resources
-l, --location location to create the bot service in (westus, ...)
--luisAuthoringKey authoring key from the appropriate luisAuthoringRegion for luis resources
--luisAuthoringRegion (OPTIONAL) [westus|westeurope|australiaeast] authoring region to put LUIS models into (default is based on location)
--luisPublishRegion (OPTIONAL) region to publish LUIS models to (default fallback is based location || luisAuthoringRegion)
--subscriptionId (OPTIONAL) Azure subscriptionId to clone bot to, if not passed then current az account will be used
--insightsRegion (OPTIONAL) region to create appInsights account in (default is based on location)
--groupName (OPTIONAL) groupName for cloned bot, if not passed then new bot name will be used for the new group
--sdkLanguage (OPTIONAL) language for bot [Csharp|Node] (Default:CSharp)
--sdkVersion (OPTIONAL) SDK version for bot [v3|v4] (Default:v4)
-q, --quiet minimize output
--verbose show commands
-f, --force do not prompt for confirmation
-h, --help output usage information
[msbot] NOTE: You did not complete clone process.
[msbot] To delete the group and resources run:
[msbot] az group delete -g SB_EnterpriseBot --no-wait

### PR DESCRIPTION
**Pull request by darrenj**
Fixes #596 

## Proposed Changes

Add appId and appSecret parameters to msbot clone services which is then passed into az bot create. This provides a workaround to the auto-provision of applicationIds/Secrets being experienced by customers

image

### CODE REVIEW

**Comment by muges01** [comment]
is this fix been released? Is this available on the npm for me to install?

**Comment by mekinney** [comment]
>           Is this fix has been released? Is it available on the npm for me to install?

Doesn't appear to have been for me.

**Comment by ShawnXiao105** [comment]
I still cannot pass msbot clone service even if I set appId and appSecret. And I found another bug that if the appSecret contains two sequences | like ||. The program just misses the part after the ||. Thanks

**Comment by darrenj** [comment]
I suspect that issue is because your not wrapping the secret with quotes and therefore breaks argument parsing. if you do --appSecret "YOUR_SECRET" you should be OK. Can you create a bug over [here](https://github.com/Microsoft/ai) with more details of what you are hitting even when using the parameters.

We are working on a fix to msbot clone to address the auto provision issue, testing soon.

**Pull request merged**
