### PR TITLE
[LUIS] Fix querylogs download handling 

### LINKED ISSUE #627: Unable to use the command line luis list querylogs
## Tool
Name: LUIS
Version: 2.0.13
OS: Windows 10

## Describe the bug
When using the command line "luis list querylogs" I have the following error:
```
Unknown resource: querylogs

LUIS Command Line Interface - © 2018 Microsoft Corporation

Gets the query logs of the past month for the application.

Usage:
luis list querylogs --appId <string>

Command arguments are:
 --appId <string>          The application ID.
 (required)
```

## To Reproduce
1. Have a completed .luisrc file with your app infos
2. run the command `luis list querylogs`

## Expected behavior
A list of the query logs of the past month

## Additional context
I used Postman to test if I could fetch the logs with a simple Get and I was able to do it using my appId and subscription key. I also tried to add the appId to the command line and still no luck. I can use `luis list versions` ou `luis get settings` without any issue.

[bug]

### PR DESCRIPTION
**Pull request by enzocanoo**
Fixes #627

## Proposed Changes
  - Add `list querylogs` case for `luis.js`.
  - Handle streamed responses from `ms-rest-js`.

`luis list querylogs` csv response
image

### CODE REVIEW

**Comment by cleemullins** [comment]
@Zerryth Can you review + test this change, and approve when ready? If it's good, please merge it in.

**Comment by cleemullins** [comment]
@enzocanoo This looks great - thanks for jumping in! As Ashley (@Zerryth) has been digging into this, I would like to see her review / test / then merge, just so she get a chance to go through the full lifecycle.

**Comment by Zerryth** [comment]
@cleemullins took a look, and it does handle the incoming stream data by outputting it into the terminal

```
Query,UTC DateTime,Response
move wayne berry from miami to mount vernon,10/01/2018 22:36:29,"{""query"":""Move wayne berry from miami to mount vernon"",""intents"":[{""intent"":""ApplyForJob"",""score"":5.846154E-10},{""intent"":""EmployeeFeedback"",""score"":1.68E-09},{""intent"":""FindForm"",""score"":1.26923072E-09},{""intent"":""GetJobInformation"",""score"":6.18181446E-07},{""intent"":""Introduction"",""score"":8.88881E-06},{""intent"":""MoveEmployee"",""score"":8.452943E-07},{""intent"":""NewEmployeeRelocationProcess"",""score"":0.9999999},{""intent"":""None"",""score"":3.46E-09},{""intent"":""OrgChart-Manager"",""score"":2.86666668E-09},{""intent"":""OrgChart-Reports"",""score"":2.86666668E-09},{""intent"":""Utilities.Cancel"",""score"":1.38333334E-09},{""intent"":""Utilities.Confirm"",""score"":1.53351459E-06},{""intent"":""Utilities.Help"",""score"":1.5181818E-09},{""intent"":""Utilities.StartOver"",""score"":1.68E-09},{""intent"":""Utilities.Stop"",""score"":1.5181818E-09}],""entities"":[{""entity"":""wayne berry"",""type"":""NewEmployee"",""startIndex"":5,""endIndex"":15,""score"":0.9438736,""role"":""""},{""entity"":""miami"",""type"":""NewEmployeeRelocation"",""startIndex"":22,""endIndex"":26,""score"":0.9750006,""role"":""NewEmployeeReloOrigin""},{""entity"":""mount vernon"",""type"":""NewEmployeeRelocation"",""startIndex"":31,""endIndex"":42,""score"":0.993747234,""role"":""NewEmployeeReloDestination""},{""entity"":""wayne berry"",""type"":""builtin.keyPhrase"",""startIndex"":5,""endIndex"":15},{""entity"":""miami"",""type"":""builtin.keyPhrase"",""startIndex"":22,""endIndex"":26}],""sentimentAnalysis"":{""label"":""neutral"",""score"":0.5}}"
who is the boss of jill jones?,10/01/2018 20:48:28,"{""PatternMatches"":null,""query"":""Who is the boss of Jill Jones?"",""intents"":[{""intent"":""ApplyForJob"",""score"":5.423077E-10},{""intent"":""EmployeeFeedback"",""score"":4.85564669E-06},{""intent"":""FindForm"",""score"":1.18461541E-09},{""intent"":""GetJobInformation"",""score"":5.73737054E-07},{""intent"":""Introduction"",""score"":8.333264E-06},{""intent"":""MoveEmployee"",""score"":7.868149E-07},{""intent"":""None"",""score"":0.0009710561},{""intent"":""OrgChart-Manager"",""score"":0.999994159},{""intent"":""OrgChart-Reports"",""score"":2.98139257E-05},{""intent"":""Utilities.Cancel"",""score"":1.29166666E-09},{""intent"":""Utilities.Confirm"",""score"":1.41818179E-09},{""intent"":""Utilities.Help"",""score"":1.41818179E-09},{""intent"":""Utilities.StartOver"",""score"":1.57E-09},{""intent"":""Utilities.Stop"",""score"":1.41818179E-09}],""entities"":[{""entity"":""jill jones"",""type"":""Employee"",""startIndex"":19,""endIndex"":28,""resolution"":{""values"":[""Employee-45612""]},""role"":""""},{""entity"":""boss of
jill jones"",""type"":""builtin.keyPhrase"",""startIndex"":11,""endIndex"":28}],""sentimentAnalysis"":{""label"":""neutral"",""score"":0.5}}"
displace 425 - 555 - 0000 away from g - 2323 toward hh- 2345,10/02/2018 20:37:23,"{""query"":""displace 425 - 555 - 0000 away from g - 2323 toward hh- 2345"",""intents"":[{""intent"":""ApplyForJob"",""score"":0.00363327283},{""intent"":""EmployeeFeedback"",""score"":0.01027843},{""intent"":""FindForm"",""score"":0.00361073087},{""intent"":""GetJobInformation"",""score"":0.0114271119},{""intent"":""Introduction"",""score"":0.0014278061},{""intent"":""MoveEmployee"",""score"":0.973650634},{""intent"":""NewEmployeeRelocationProcess"",""score"":0.00536705134},{""intent"":""None"",""score"":0.00149790349},{""intent"":""OrgChart-Manager"",""score"":0.00136380328},{""intent"":""OrgChart-Reports"",""score"":0.0010241546},{""intent"":""Utilities.Cancel"",""score"":0.00524655031},{""intent"":""Utilities.Confirm"",""score"":1.48351783E-05},{""intent"":""Utilities.Help"",""score"":0.0008600038},{""intent"":""Utilities.StartOver"",""score"":0.00172363746},{""intent"":""Utilities.Stop"",""score"":0.000292873476}],""entities"":[{""entity"":""hh - 2345"",""type"":""Locations::Destination"",""startIndex"":52,""endIndex"":59,""score"":0.967129767},{""entity"":""g - 2323"",""type"":""Locations::Origin"",""startIndex"":36,""endIndex"":43,""score"":0.9552336},{""entity"":""425 - 555 - 0000 away from g - 2323 toward hh - 2345"",""type"":""requestemployeemove"",""startIndex"":9,""endIndex"":59,""score"":0.9421177},{""entity"":""425 - 555 - 0000"",""type"":""Employee"",""startIndex"":9,""endIndex"":24,""resolution"":{""values"":[""Employee-45612""]}},{""entity"":""hh"",""type"":""builtin.keyPhrase"",""startIndex"":52,""endIndex"":53}],""compositeEntities"":[{""parentType"":""requestemployeemove"",""value"":""425 - 555 - 0000 away from g - 2323 toward hh - 2345"",""children"":[{""type"":""Locations::Destination"",""value"":""hh - 2345""},{""type"":""Locations::Origin"",""value"":""g - 2323""},{""type"":""Employee"",""value"":""425 - 555 - 0000""}]}],""sentimentAnalysis"":{""label"":""neutral"",""score"":0.5}}"
move wayne berry from newark to columbus,10/01/2018 22:34:24,"{""query"":""Move Wayne Berry from Newark to Columbus"",""intents"":[{""intent"":""ApplyForJob"",""score"":0.007243599},{""intent"":""EmployeeFeedback"",""score"":0.0016759237},{""intent"":""FindForm"",""score"":0.00111618976},{""intent"":""GetJobInformation"",""score"":0.008405463},{""intent"":""Introduction"",""score"":0.008016343},{""intent"":""MoveEmployee"",""score"":0.0098685585},{""intent"":""NewEmployeeRelocationProcess"",""score"":0.474828124},{""intent"":""None"",""score"":0.00447141053},{""intent"":""OrgChart-Manager"",""score"":0.00161790778},{""intent"":""OrgChart-Reports"",""score"":0.0019808393},{""intent"":""Utilities.Cancel"",""score"":0.004458747},{""intent"":""Utilities.Confirm"",""score"":0.016579356},{""intent"":""Utilities.Help"",""score"":0.00174081954},{""intent"":""Utilities.StartOver"",""score"":0.006063999},{""intent"":""Utilities.Stop"",""score"":0.00162341783}],""entities"":[{""entity"":""wayne berry"",""type"":""NewEmployee"",""startIndex"":5,""endIndex"":15,""score"":0.6680935},{""entity"":""newark"",""type"":""NewEmployeeRelocation"",""startIndex"":22,""endIndex"":27,""score"":0.6374548},{""entity"":""wayne berry"",""type"":""builtin.keyPhrase"",""startIndex"":5,""endIndex"":15}],""sentimentAnalysis"":{""label"":""neutral"",""score"":0.5}}"
move wayne berry from newark to columbus,10/01/2018 22:34:09,"{""query"":""Move Wayne Berry from Newark to Columbus"",""intents"":[{""intent"":""ApplyForJob"",""score"":0.007243599},{""intent"":""EmployeeFeedback"",""score"":0.0016759237},{""intent"":""FindForm"",""score"":0.00111618976},{""intent"":""GetJobInformation"",""score"":0.008405463},{""intent"":""Introduction"",""score"":0.00633862847},{""intent"":""MoveEmployee"",""score"":0.0098685585},{""intent"":""NewEmployeeRelocationProcess"",""score"":0.474828124},{""intent"":""None"",""score"":0.00447141053},{""intent"":""OrgChart-Manager"",""score"":0.00194869784},{""intent"":""OrgChart-Reports"",""score"":0.00260927272},{""intent"":""Utilities.Cancel"",""score"":0.004458747},{""intent"":""Utilities.Confirm"",""score"":0.016579356},{""intent"":""Utilities.Help"",""score"":0.00174081954},{""intent"":""Utilities.StartOver"",""score"":0.006063999},{""intent"":""Utilities.Stop"",""score"":0.00162341783}],""entities"":[{""entity"":""wayne berry"",""type"":""NewEmployee"",""startIndex"":5,""endIndex"":15,""score"":0.6680935},{""entity"":""newark"",""type"":""NewEmployeeRelocation"",""startIndex"":22,""endIndex"":27,""score"":0.6374548},{""entity"":""wayne berry"",""type"":""builtin.keyPhrase"",""startIndex"":5,""endIndex"":15}],""sentimentAnalysis"":{""label"":""neutral"",""score"":0.5}}"
move wayne berry from newark to columbus,10/01/2018 22:32:05,"{""query"":""Move Wayne Berry from Newark to Columbus"",""intents"":[{""intent"":""ApplyForJob"",""score"":0.007243599},{""intent"":""EmployeeFeedback"",""score"":0.0016759237},{""intent"":""FindForm"",""score"":0.00111618976},{""intent"":""GetJobInformation"",""score"":0.008405463},{""intent"":""Introduction"",""score"":0.00633862847},{""intent"":""MoveEmployee"",""score"":0.0098685585},{""intent"":""NewEmployeeRelocationProcess"",""score"":0.474828124},{""intent"":""None"",""score"":0.00447141053},{""intent"":""OrgChart-Manager"",""score"":0.00194869784},{""intent"":""OrgChart-Reports"",""score"":0.00260927272},{""intent"":""Utilities.Cancel"",""score"":0.004458747},{""intent"":""Utilities.Confirm"",""score"":0.016579356},{""intent"":""Utilities.Help"",""score"":0.00174081954},{""intent"":""Utilities.StartOver"",""score"":0.006063999},{""intent"":""Utilities.Stop"",""score"":0.00162341783}],""entities"":[{""entity"":""wayne berry"",""type"":""NewEmployee"",""startIndex"":5,""endIndex"":15,""score"":0.6680935},{""entity"":""newark"",""type"":""NewEmployeeRelocation"",""startIndex"":22,""endIndex"":27,""score"":0.6374548},{""entity"":""wayne berry"",""type"":""builtin.keyPhrase"",""startIndex"":5,""endIndex"":15}],""sentimentAnalysis"":{""label"":""neutral"",""score"":0.5}}"
```

Is this how we want the data to be received when running the command? (as opposed to creating a new file)
If so, it looks great! I will be sure to double check and test again, then merge

**Comment by cleemullins** [comment]
I think this is what we want, as from there one could pipe to a file "> foo.logs", or "|' to a another app such as grep. 

Changes to behavior should be taken as feature requests moving forward.

**Pull request merged**
