### PR TITLE
Improve code coverage in luis-apis

### PR DESCRIPTION
**Pull request by enzocanoo**
## Proposed Changes
 - Add .js extension to ./bin/luis file. This file was not being indexed for code coverage metrics. nyc requires that all files have an extension ([link](https://github.com/istanbuljs/nyc/issues/781#issuecomment-379497461)).
 - Add new tests related to cover other paths in `luis-apis` cli.
 - Delete unused files.

### CODE REVIEW

**Comment by justinwilaby** [comment]
files in `bin` should probably not have extensions.

**Comment by tomlm** [comment]
bin files can most definitely be .js and in fact this seems quite normal.  npm and gulp and many cli's all put .js files into the bin folder.  It's even on the sample page for the npm bin documentation that way.  Are there are objections you have to this delta?

**Comment by cleemullins** [comment]
@juanar, looks like the build is failing here as well.

**Comment by JuanAr** [comment]
PR #353 should fix the issues with this PR

**Pull request merged**
