### PR TITLE
Fix for #524

### LINKED ISSUE #524: undefined error whilst executing ludown translate
ludown tool fails with an undefined error midway through translation of a large LU file (which itself was created through the ludown refresh command.

```shell
ludown translate --in model.lu -t de-DE -k mykey -o de
```

[LUISModel.zip](https://github.com/Microsoft/botbuilder-tools/files/2392492/LUISModel.zip)

### PR DESCRIPTION
**Pull request by vishwacsena**
Fixes #524
- added one additional test
- all existing tests are passing

### CODE REVIEW

**Comment by cleemullins** [comment]
@vishwacsena Build is failing. Looks like your new test. 

(node:5696) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'urls' of undefined
    at /home/travis/build/Microsoft/botbuilder-tools/packages/Ludown/lib/parseFileContents.js:32:31
    at Array.forEach (<anonymous>)
    at collateQnAFiles (/home/travis/build/Microsoft/botbuilder-tools/packages/Ludown/lib/parseFileContents.js:31:163)
    at Context.<anonymous> (/home/travis/build/Microsoft/botbuilder-tools/packages/Ludown/test/ludown.qnafiles.test.suite.js:35:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
(node:5696) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm ERR! code ELIFECYCLE
npm ERR! errno 10
npm ERR! ludown@1.0.35 test: `cd test/ && mocha --opts mocha.opts`

**Comment by vishwacsena** [comment]
@cleemullins - the offending test needed a fix. All tests are passing locally. Hope this round will go through clean with the build.

**Comment by vishwacsena** [comment]
@cleemullins - the build is failing again with ludown translate tests. Are these using my personal translate key? If so, looks like Tom yanked out the key I had created in the PPE subscription. I ran into this issue today when testing Darren's ginormous lu file with over 15K lines of utterances. So 
1. We should switch to a team key and not use my personal key 
2. I do not know how/ where this is getting picked up from. 

In any case, I created a new key off our PPE subscription and emailed you the key. Can we restart the tests with the updated key?

**Comment by cleemullins** [comment]
@tomlm has updated the build, so things *should* pass. kicking off a new build.

**Pull request merged**
