### PR TITLE
rewrote msbot to use botframework-config package and added unit tests

### PR DESCRIPTION
**Pull request by tomlm**
added unit tests for all command line switches

### CODE REVIEW

**Comment by justinwilaby** [comment]
Looks like sourcemaps are making it in `bin/`. These are just noise and should be added to the gitignore. Better yet, we should omit built files from the repo altogether.

**Comment by cleemullins** [comment]
@tomlm, can you address issues in the PR so we can get it merged in? Love the new test coverage!

**Comment by vishwacsena** [comment]
Functional issue - >msbot get
module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\repos\v4SDK\botbuilder-js\samples\14.nlp-with-dispatch\msbot-get'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by vishwacsena** [comment]
Functional issue - Luis import application --in luismodel.json --msbot | msbot connect luis --stdin no longer works with Error: bad or missing –appId.

**Pull request merged**
